### ISSUE TITLE
SSL Certificate Issues (Sep 2021)

### ISSUE THREAD

**Issue by rverrips** [circinusX1/Free-Key-Value-Database#1]
Hi 
I just discovered your service today and am very interested. 
When testing it out for first time  today (Sep 10, 2021) I am unable to complete any requests due to an SSL Certificate problem on the server? 
Please let me know if I'm doing anything wrong. 
Thanks
Roy

```
curl https://meeiot.org/get/5ba8e5788973226b3255844b37221c2a0f8a3921784b8cf1c93b9f

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

**Comment by circinusX1** [comment]
Hi,
The certificate kind-of looks ok. COUld be because I am using the free:
CERTBOOT and the issuer is now untrusted ?

You can bypass the validity for trusted issuer by

curl -k
https://meeiot.org/get/5ba8e5788973226b3255844b37221c2a0f8a3921784b8cf1c93b9f
myvalue

[image: image.png]


[image: image.png]


[image: image.png]

**Comment by circinusX1** [comment]
You should generate another ID as long the old ID is public here.
Let me know so I can delete the previous posts

**Comment by circinusX1** [comment]
Hi,
use -k to bypass the [CERTBOOT](https://certbot.eff.org/) generated certificates authority

```
curl -k  https://meeiot.org/get/5ba8e5788973226b3255844b37221c2a0f8a3921784b8cf1c93b9f
myvalue
```

**Comment by rverrips** [comment]
Thank you for looking into this - you could try 'let's encrypt' as an alternative SSL provider which is also free but trusted more widely. 

I was hoping to call the keyvalue API as a counter from within a JavaScript App, so I ended up just writing a similar service for myself.
